// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_lasso_sum_ess_gps
List fast_lasso_sum_ess_gps(const Eigen::VectorXd& uVec, const Eigen::MatrixXd& xTx, int n, const Eigen::VectorXi& group, const Eigen::VectorXd& lambda, const Eigen::VectorXd& alpha, const Eigen::VectorXd& eta, const Eigen::VectorXd& bccVec, const Eigen::VectorXd& initVec, const int maxIter);
RcppExport SEXP _GPS_fast_lasso_sum_ess_gps(SEXP uVecSEXP, SEXP xTxSEXP, SEXP nSEXP, SEXP groupSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP etaSEXP, SEXP bccVecSEXP, SEXP initVecSEXP, SEXP maxIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type uVec(uVecSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type xTx(xTxSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type bccVec(bccVecSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type initVec(initVecSEXP);
    Rcpp::traits::input_parameter< const int >::type maxIter(maxIterSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_lasso_sum_ess_gps(uVec, xTx, n, group, lambda, alpha, eta, bccVec, initVec, maxIter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GPS_fast_lasso_sum_ess_gps", (DL_FUNC) &_GPS_fast_lasso_sum_ess_gps, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_GPS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
