# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title core function for fast coordinate descent of GPS loss function
#' @param uVec u statistics (x'y)
#' @param xTx x_transpose_x matrix calculated from reference panel
#' @param n sample size;
#' @param group 1-based group indicator that indicates which alpha and lambda to use
#' @param alpha l1 penalty parameter options, match unique group id
#' @param lambda l2 penalty parameter options, match unique group id
#' @param eta l2 penalty parameter for deviation from prior (correlated) effect size estimates
#' @param bccVec weight of PRS for a correlated trait to serve as a prior
#' @param initVec initial value of beta (joint effect)
#' @param maxIter maximum number of iterations
#' @return a list where `beta` is the fitted regression coefficient vector, and `iteration` is the actual iteration.
fast_lasso_sum_ess_gps <- function(uVec, xTx, n, group, lambda, alpha, eta, bccVec, initVec, maxIter = 100L) {
    .Call(`_gps_fast_lasso_sum_ess_gps`, uVec, xTx, n, group, lambda, alpha, eta, bccVec, initVec, maxIter)
}

